name: Dependabot Auto-Merge

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' # Ensure this only runs for Dependabot PRs

    steps:
      # Fetch Dependabot metadata
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.AUTO_TOKEN }}"

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm test

      # Check Vercel preview deployment
      - name: Check Vercel Deployment
        run: |
          DEPLOYMENT_URL="https://team-portfolio-git-${{ github.head_ref }}-rxshabns-projects.vercel.app"
          echo "Checking Vercel deployment at $DEPLOYMENT_URL"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$DEPLOYMENT_URL")
          if [[ $HTTP_STATUS -ne 200 ]]; then
            echo "Vercel deployment failed with status code $HTTP_STATUS."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.AUTO_TOKEN }}

      # Enable auto-merge if conditions are met
      - name: Enable auto-merge
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' && success()
        run: gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.AUTO_TOKEN }}
